---
kind: Service
apiVersion: v1
metadata:
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: keepalived-operator/keepalivedgroup-infra
  name: httpd-extip
  namespace: my-test-namespace
  labels:
    app: httpd
spec:
  ports:
    - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
    - name: 8443-tcp
    protocol: TCP
    port: 8443
    targetPort: 8443
  selector:
    app: httpd
    deploymentconfig: httpd
  type: ClusterIP
  externalIPs:
    - 10.0.0.34
  sessionAffinity: None
...
