---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      volumeClaimTemplate:
        metadata:
          name: prometheus-pvc
        spec:
          resources:
            requests:
              storage: 100Gi
          selector:
            matchLabels:
              infrapvc: "prometheus"
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-pvc
        spec:
          resources:
            requests:
              storage: 20Gi
          selector:
            matchLabels:
              infrapvc: "alertmanager"
...