---
apiVersion: v1
data:
  tls.crt: <BASE64-ENCODED-TLS-CRT> 
  tls.key: <BASE64-ENCODED-TLS-KEY>
kind: Secret
metadata:
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  name: sealed-secret-custom-cert
  namespace: sealed-secrets
type: kubernetes.io/tls
...
