---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: sealed-secrets
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sealed-secrets
    name: sealed-secrets-controller
  type: ClusterIP
...
