---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: sealed-secrets
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: sealed-secrets
...
